-- Adding sample job listings for testing
INSERT INTO jobs (
  title, company, location, type, salary_min, salary_max, description, requirements, benefits,
  remote_work, experience_level, application_email, tags, featured
) VALUES 
(
  'Développeur Full Stack React/Node.js',
  'TechCorp France',
  'Paris, France',
  'CDI',
  45000,
  65000,
  'Nous recherchons un développeur full stack passionné pour rejoindre notre équipe dynamique. Vous travaillerez sur des projets innovants utilisant les dernières technologies.',
  'Expérience avec React, Node.js, TypeScript, PostgreSQL. Connaissance des pratiques DevOps appréciée.',
  'Télétravail partiel, tickets restaurant, mutuelle, formation continue',
  true,
  'Confirmé',
  'recrutement@techcorp.fr',
  ARRAY['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'JavaScript'],
  true
),
(
  'Designer UX/UI Senior',
  'Creative Studio',
  'Lyon, France',
  'CDI',
  40000,
  55000,
  'Rejoignez notre studio créatif en tant que Designer UX/UI Senior. Vous concevrez des expériences utilisateur exceptionnelles pour nos clients.',
  'Maîtrise de Figma, Adobe Creative Suite, expérience en design system, portfolio requis.',
  'Environnement créatif, projets variés, équipe jeune et dynamique',
  false,
  'Senior',
  'jobs@creativestudio.fr',
  ARRAY['Figma', 'Adobe XD', 'Photoshop', 'UX Design', 'UI Design'],
  false
),
(
  'Développeur Mobile Flutter',
  'MobileFirst',
  'Remote, France',
  'Freelance',
  400,
  600,
  'Mission freelance pour développer une application mobile innovante avec Flutter. Projet de 6 mois renouvelable.',
  'Expertise Flutter/Dart, expérience avec Firebase, connaissances en architecture mobile.',
  'Mission 100% remote, projet innovant, équipe internationale',
  true,
  'Confirmé',
  'contact@mobilefirst.com',
  ARRAY['Flutter', 'Dart', 'Firebase', 'Mobile', 'iOS', 'Android'],
  false
),
(
  'Stage Développement Web',
  'StartupTech',
  'Bordeaux, France',
  'Stage',
  800,
  1200,
  'Stage de 6 mois dans une startup en pleine croissance. Vous participerez au développement de notre plateforme web.',
  'Étudiant en informatique, bases en HTML/CSS/JavaScript, motivation et curiosité.',
  'Encadrement personnalisé, possibilité d''embauche, environnement startup',
  false,
  'Junior',
  'stage@startuptech.fr',
  ARRAY['HTML', 'CSS', 'JavaScript', 'Vue.js', 'Stage'],
  false
),
(
  'Ingénieur Cloud',
  'Cloud Solutions',
  'Marseille, France',
  'CDI',
  50000,
  70000,
  'Nous sommes à la recherche d''un ingénieur cloud pour gérer et optimiser nos infrastructures cloud.',
  'Expérience avec AWS, Azure, Google Cloud, Kubernetes, Docker.',
  'Formation continue, environnement de travail moderne, équipe compétente',
  true,
  'Confirmé',
  'recrutement@cloudsolutions.fr',
  ARRAY['AWS', 'Azure', 'Google Cloud', 'Kubernetes', 'Docker'],
  true
);
